### ISSUE TITLE
the program crashes when I get out of it

### ISSUE THREAD

**Issue by RoundCat98** [serge-rgb/milton#77] opened 2018-01-31 15:35 UTC
windows 8.1 russian
Milton v1.5.1
If I try to exit through file-> Quit or through red cross program crash and does not respond, then I have to manually close program in task manager
![11111](https://user-images.githubusercontent.com/32231035/35631616-619cfc6e-06b5-11e8-9979-459dfe061d05.PNG)

**Comment by serge-rgb** [comment] 2018-02-01 04:38
Probably a duplicate of #64. This should be fixed on the next release!

**Closed by serge-rgb** 2018-02-01 04:38 UTC
