### ISSUE TITLE
Brush cursor not visible

### ISSUE THREAD

**Issue by anjanjanj** [serge-rgb/milton#48] opened 2017-03-25 07:42 UTC
My cursor is entirely invisible when inside the canvas area using Milton 1.2.8 on Windows 7. There is no outline of the brush cursor. This makes it impossible to see where I'm about to paint before clicking.

**Comment by serge-rgb** [comment] 2017-03-26 18:18
This is a duplicate of #43. It should be fixed in the next release. 
Thanks for reporting

**Closed by serge-rgb** 2017-03-26 18:18 UTC
