### ISSUE TITLE
Can't build on a modern machine (x64, Win 10), followed Readme

### ISSUE THREAD

**Issue by h3rb** [serge-rgb/milton#19] opened 2016-10-09 00:51 UTC
Hi, found you guys via Handmade Hero (Casey)

When following the build instructions, I made no modifications because they were already in place:

`C:\Users\h3rb\Downloads\milton-master\milton-master\scripts>cd ..

C:\Users\h3rb\Downloads\milton-master\milton-master>scripts\vcvars.bat

C:\Users\h3rb\Downloads\milton-master\milton-master>build
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

ctime.c
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:ctime.exe
ctime.obj
winmm.lib
        1 file(s) copied.
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

```
    1 file(s) copied.
    1 file(s) copied.
```

   [BUILD] -- Building Milton...
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

shadergen.cc
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:shadergen.exe
/debug
shadergen.obj
milton_unity_build.cc
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_SetClipboardText referenced in function "void __cdecl ImGui_ImplSdlGL3_SetClipboardText(char const *)" (?ImGui_ImplSdlGL3_SetClipboardText@@YAXPBD@Z)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GetClipboardText referenced in function "char const \* __cdecl ImGui_ImplSdlGL3_GetClipboardText(void)" (?ImGui_ImplSdlGL3_GetClipboardText@@YAPBDXZ)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GetSystemRAM referenced in function "unsigned int __cdecl get_system_RAM(void)" (?get_system_RAM@@YAIXZ)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_CreateWindow referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GetWindowID referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GetWindowFlags referenced in function "void __cdecl ImGui_ImplSdlGL3_NewFrame(void)" (?ImGui_ImplSdlGL3_NewFrame@@YAXXZ)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GetWindowSize referenced in function "void __cdecl ImGui_ImplSdlGL3_NewFrame(void)" (?ImGui_ImplSdlGL3_NewFrame@@YAXXZ)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GL_SetAttribute referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GL_CreateContext referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GL_SetSwapInterval referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GL_SwapWindow referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GetModState referenced in function "bool __cdecl ImGui_ImplSdlGL3_ProcessEvent(union SDL_Event *)" (?ImGui_ImplSdlGL3_ProcessEvent@@YA_NPATSDL_Event@@@Z)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GetKeyFromScancode referenced in function "enum LayoutType __cdecl get_current_keyboard_layout(void)" (?get_current_keyboard_layout@@YA?AW4LayoutType@@XZ)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GetMouseState referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_CreateCursor referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_CreateSystemCursor referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_SetCursor referenced in function "void __cdecl cursor_set_and_show(struct SDL_Cursor *)" (?cursor_set_and_show@@YAXPAUSDL_Cursor@@@Z)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_ShowCursor referenced in function "void __cdecl ImGui_ImplSdlGL3_NewFrame(void)" (?ImGui_ImplSdlGL3_NewFrame@@YAXXZ)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_PollEvent referenced in function "struct MiltonInput __cdecl sdl_event_loop(struct MiltonState *,struct PlatformState *)" (?sdl_event_loop@@YA?AUMiltonInput@@PAUMiltonState@@PAUPlatformState@@@Z)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_WaitEvent referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_EventState referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GetTicks referenced in function "void __cdecl milton_update_and_render(struct MiltonState *,struct MiltonInput *)" (?milton_update_and_render@@YAXPAUMiltonState@@PAUMiltonInput@@@Z)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_Delay referenced in function "void __cdecl milton_update_and_render(struct MiltonState *,struct MiltonInput *)" (?milton_update_and_render@@YAXPAUMiltonState@@PAUMiltonInput@@@Z)
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_Init referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_Quit referenced in function _milton_main
milton_unity_build.obj : error LNK2019: unresolved external symbol _SDL_GetWindowWMInfo referenced in function _milton_main
SDL2.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'X86'
Milton.exe : fatal error LNK1120: 26 unresolved externals
   [FATAL] -- ... Error building Milton`

**Comment by ancrist** [comment] 2016-10-10 17:39
The problem is that the build.bat script indiscriminately copies the x64 version of SDL2.lib into the build directory.

A quick workaround would be to replace the following two lines in build.bat:
```Batchfile
IF NOT EXIST build\SDL2.lib copy third_party\bin\SDL2.lib build\SDL2.lib
IF NOT EXIST build\SDL2.pdb copy third_party\bin\SDL2.pdb build\SDL2.pdb
```
with the these:

```Batchfile
IF NOT EXIST build\SDL2.lib copy third_party\bin\x86\SDL2.lib build\SDL2.lib
IF NOT EXIST build\SDL2.pdb copy third_party\bin\x86\SDL2.pdb build\SDL2.pdb
```
That should fix the build. Just remember to change the lines back to their original values if doing an x64 build.

@h3rb 
Maybe have the **build.bat** script copy the appropriate libraries based on the target architecture specified via a command line argument... something like:

`
build <x86  | x64>
`

**Comment by serge-rgb** [comment] 2016-10-10 22:23
It's a mistake on my part. Almost all the time, I set scripts\vcvars.bat to set up a x64 environment, but the latest commit is left as x86. Personally I only care about x86 when doing a release.

I think the solution is to have build.bat check for the machine type of the current msvc compiler and automatically do the right thing. For now, I'll just try and make sure that the build compiles before pushing to github.. :)

**Comment by serge-rgb** [comment] 2017-01-15 22:22
Closing issue. This should not be a problem once the migration to the tundra build system is complete.

**Closed by serge-rgb** 2017-01-15 22:22 UTC
