### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by gonutz** [serge-rgb/milton#129] opened 2019-09-02 12:28 UTC
I would love to work on this code base but I cannot get it to compile. I have Visual Studio 2019 installed but you only provide a `build.bat` which assumes that `cl.exe` is located in my PATH. This is not the case, unfortunately. Visual Studio is not really transparent when it comes to locating their tools, I found four folders with `cl.exe`s them.

I then used the "developer command line" and called `build` as well as `build x86` but both failed, the 64 bit build with

> unity.obj : error LNK2019: unresolved external symbol _SDL_free referenced in function "void __cdecl ImGui_ImplSDL2_Shutdown(void)" (?ImGui_ImplSDL2_Shutdown@@YAXXZ)
...

and the 32 bit build with

> unity.obj
LIBCMTD.lib(ftol2.obj) : error LNK2005: __ftol2_sse already defined in SDL2.lib(SDL_stdlib.obj)

I have abandoned C++ many years ago and this is exactly why. Why can't we have nice things? I would love to be able to just compile the code, work on it and compile again until my desired feature (text input with the keyboard) is done.

Could you please find and document an easy and reproducible way to build the code? I would really appreciate it! :-)

**Comment by serge-rgb** [comment] 2019-09-05 23:46
Calling build.bat from the VS2019 command line should work. These days I'm using VS2019 without problems, I call vcvarsall.bat from a cmd.exe instead of directly opening the "developer command line". I'll see if I can get a repro tonight.
I agree that building C++ is in general a horrible experience. I'll update the README.md and see if I can reproduce the problem

**Comment by serge-rgb** [comment] 2019-09-06 04:12
Yeah... Looks like the "Developer Command Prompt for VS 2019" defaults to the x86 compiler and not the x64 one. Try opening the "x64 Native Tools Command Prompt" and build from there

**Comment by serge-rgb** [comment] 2019-09-06 04:14
Updated README.md. Closing this issue

**Closed by serge-rgb** 2019-09-06 04:14 UTC

**Comment by gonutz** [comment] 2019-09-06 09:23
Great, thanks for the quick update. This works now for me. However I can only build 64 bit targets, I tried all four developer consoles that come with VS19 but none are able to successfully run `build x86`. You might want to look into that.
