### ISSUE TITLE
Can't see the brush cursor

### ISSUE THREAD

**Issue by thecosss** [serge-rgb/milton#51] opened 2017-05-11 14:17 UTC
Win 10. Milton 1.2.8

**Comment by Bobo1239** [comment] 2017-05-11 15:45
Duplicate of #43. Should be fixed in the next release.

**Comment by serge-rgb** [comment] 2017-05-17 03:22
What @Bobo1239 said. 
Also, there's (finally) a new release with this bug hopefully fixed. I'm closing the issue but please reopen if the bug is still present.

**Closed by serge-rgb** 2017-05-17 03:22 UTC
