### ISSUE TITLE
Doesn't draw with Huion WH1409

### ISSUE THREAD

**Issue by MrMontolio** [serge-rgb/milton#87] opened 2018-04-13 23:22 UTC
I can move the pointer around with my stylus on the program, but it doesn't trace any line when touching the tip. I'm using Windows 10 Pro.

**Comment by delscorcho** [comment] 2018-07-14 23:33
Same problem also with a Huion tablet. I can draw in everything else, but the cursor doesn't move when Milton has focus.

**Comment by delscorcho** [comment] 2018-08-20 20:44
I fixed this for my case with a small code change. It actually seemed to be more related to multiple monitors that necessary the Huion tablet, but I don't have any other tablets to compare against so I can't confirm. If others can confirm this change works fine with their setup, perhaps it's worthy of a pull request.

Look for the **#if 1** below.

`
EasyTabResult EasyTab_HandleEvent(HWND Window, UINT Message, LPARAM LParam, WPARAM WParam)
{
    EasyTabResult result = EASYTAB_EVENT_NOT_HANDLED;

    PACKET PacketBuffer[EASYTAB_PACKETQUEUE_SIZE] = {0};

    // Bring our context to the top.
    if (EasyTab && EasyTab->WTOverlap)
    {
       EasyTab->WTOverlap(EasyTab->Context, TRUE);
    }

    EasyTab->NumPackets = 0;
    #ifdef MILTON_EASYTAB
        if (Message == WT_PACKET)
    #else
        if (Message == WT_PACKET &&
            (HCTX)LParam == EasyTab->Context)
    #endif
    {
        int NumPackets = EasyTab->WTPacketsGet(EasyTab->Context, EASYTAB_PACKETQUEUE_SIZE, PacketBuffer);
        POINT PointBuffer[EASYTAB_PACKETQUEUE_SIZE] = { 0 };

        if ( NumPackets ) { EasyTab->Buttons = 0; }
        for (int i = 0; i < NumPackets; ++i)
        {
#if 1       // This worked for my multi-monitor setup. Only tested with Huion tablet.
            
            PointBuffer[i].x = PacketBuffer[i].pkX;
            PointBuffer[i].y = PacketBuffer[i].pkY;

#else       // Original code.
            
            float x = (PacketBuffer[i].pkX - EasyTab->InputOriginX) / (float)EasyTab->InputExtentX;
            float y = (PacketBuffer[i].pkY - EasyTab->InputOriginY) / (float)EasyTab->InputExtentY;

            PointBuffer[i].x = EasyTab->ScreenOriginX + x * EasyTab->ScreenExtentX;
            PointBuffer[i].y = EasyTab->ScreenOriginY + y * EasyTab->ScreenExtentY; 
#endif
`

**Comment by serge-rgb** [comment] 2018-08-22 03:46
Hmmm.. I think I added the InputOrigin / InputExtent thing to support custom non-full-monitor wacom-to-screen-area mappings. I would be happy if this also covers that case though!

**Comment by delscorcho** [comment] 2018-08-22 05:10
Yeah, I wouldn't trust my change against configurations other than mine since I can't test anything else. :)

I can confirm that at least with Huion, the change fixed my issue (I wasn't able to draw in Milton regardless of which monitor and settings I tried).

**Comment by serge-rgb** [comment] 2019-03-14 03:37
I think this issue should be fixed in master now

**Closed by serge-rgb** 2019-03-14 03:37 UTC
